### ISSUE TITLE
Crash with 0.44.12-r1 and 6.54 on linux

### ISSUE THREAD

**Issue by carewolf** [mifki/df-twbt#87]
I get a reproducible crash with a backtrace that looks something like:
(gdb) bt
#0  0x0000000000000000 in  ()
#1  0x0000000000d9c184 in  ()
#2  0x0000000000d9e040 in  ()
#3  0x0000000000daa035 in  ()
#4  0x000000000074fa5a in  ()
#5  0x00007fffd718fa34 in dwarfmode_hook::interpose_fn_logic() ()
    at /mnt/nvme/games/LinuxLNP-0.44.12-r01/df_linux/hack/plugins/twbt.plug.so
#6  0x00007ffff699beb2 in interfacest::loop() () at /mnt/nvme/games/LinuxLNP-0.44.12-r01/df_linux/libs/libgraphics.so
#7  0x00000000009ccdee in mainloop() ()
#8  0x00007ffff69801c5 in enablerst::async_loop() ()
    at /mnt/nvme/games/LinuxLNP-0.44.12-r01/df_linux/libs/libgraphics.so
#9  0x00007ffff69804e0 in call_loop(void*) () at /mnt/nvme/games/LinuxLNP-0.44.12-r01/df_linux/libs/libgraphics.so
#10 0x00007ffff6f8ee18 in  () at /usr/lib/x86_64-linux-gnu/libSDL-1.2.so.0
#11 0x00007ffff6fcdf69 in  () at /usr/lib/x86_64-linux-gnu/libSDL-1.2.so.0
#12 0x00007ffff53c75aa in start_thread (arg=0x7fffe8402700) at pthread_create.c:463
#13 0x00007ffff5d49cbf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

I got it with twbt 6.53 and tried upgrading to 6.54 but it didn't help

**Comment by pronvit** [comment]
So.. how do I reproduce it?

**Comment by Chais** [comment]
I seem to reliably be able to reproduce this (or something similar, haven't checked the stacktrace) with the latest GemSet. World starts loading but at some point I get garbled text and the game freezes.
